[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm build",
  "cp -r .next/static .next/standalone/.next/static",
  "cp -r public .next/standalone/public"
]

[variables]
HOSTNAME = "0.0.0.0"

[start]
cmd = "node .next/standalone/server.js"
